GET http://localhost:8088/users/list

<> 2019-07-06T044216.200.txt

###

PUT http://localhost:8088/user/pet
Content-Type: application/json

{
  "Name": "Petya",
  "Phone": "1234567890"
}

###

GET http://localhost:8088/users/list

<> 2019-07-06T044150.200.txt

###

PUT http://localhost:8088/user/pet
Content-Type: application/json

{
  "Name": "Petya",
  "Phone": "0987654321"
}

###

POST http://localhost:8088/user/
Content-Type: application/json

{
  "Name": "Pet1",
  "Phone": "0987654321"
}

###

GET http://localhost:8088/users/list

<> 2019-07-06T041636.200.txt

###

DELETE http://localhost:8088/user/Pet1

###

GET http://localhost:8088/users/list

<> 2019-07-06T041628.200.txt

###

POST http://localhost:8088/user/
Content-Type: application/json

{
  "Name": "Pet1",
  "Phone": "0987654321"
}

###

POST http://localhost:8088/user/
Content-Type: application/json

{
  "Name": "Pet",
  "Phone": "0987654321"
}

###

GET http://localhost:8088/users/list

<> 2019-07-06T041610.200.txt

###

DELETE http://localhost:8088/user/Pet

###

DELETE http://localhost:8088/users/Pet

<> 2019-07-06T041557.404.txt

###

GET http://localhost:8088/users/list

<> 2019-07-06T041548.200.txt

###

GET http://localhost:8088/user/pet

###

GET http://localhost:8088/users/list

<> 2019-07-06T041521.200.txt

###

POST http://localhost:8088/user/
Content-Type: application/json

{
  "Name": "Pet",
  "Phone": "0987654321"
}

###

GET http://localhost:8088/users/list

<> 2019-07-06T041511.200.txt

###

GET http://localhost:8088/users/1

DELETE http://localhost:8088/users/Petya

<> 2019-07-06T035417.404.txt

###

GET http://localhost:8088/users/list/

<> 2019-07-06T035320.200.txt

###

DELETE http://localhost:8088/users/Petya

<> 2019-07-06T035316.404.txt

###

GET http://localhost:8088/users/list/

<> 2019-07-06T035242.200.txt

###

DELETE http://localhost:8088/users/1

<> 2019-07-06T035234.404.txt

###

GET http://localhost:8088/users/list/

<> 2019-07-06T035137.200.txt

###

POST http://localhost:8088/user/
Content-Type: application/json

{
  "Name": "Pet",
  "Phone": "0987654321"
}

###

POST http://localhost:8088/user/
Content-Type: application/json

{
  "Name": "Petya",
  "Phone": "0987654321"
}

###

GET http://localhost:8088/users/list/

<> 2019-07-05T121638.200.txt

###

POST http://localhost:8088/user/
Content-Type: application/json

{
  "Name": "Petya",
  "Phone": "0987654321"
}

###

GET http://localhost:8088/users/list/

<> 2019-07-05T121608.200.txt

###

POST http://localhost:8088/user/
Content-Type: application/json

{
  "Name": "Vasya",
  "Phone": "1234567890"
}

###

GET http://localhost:8088/users/list/

<> 2019-07-04T115106.200.txt

###

