GET http://localhost:8088/users/list/

###

POST http://localhost:8088/user/
Content-Type: application/json

{
  "Name": "Pet1",
  "Phone": "0987654321"
}

###

GET http://localhost:8088/user/pet

###

GET http://localhost:8088/users/list

###

DELETE http://localhost:8088/user/Pet1

###

PUT http://localhost:8088/user/pet
Content-Type: application/json

{
  "Name": "Petya",
  "Phone": "1234567890"
}

###